// Package transport implements Warren's L1 protocol camouflage layer.
//
// A Warren client's first packet is a syntactically valid TLS 1.3 ClientHello
// (built with uTLS so it carries a current browser's fingerprint, including the
// hybrid post-quantum key share mainstream browsers now offer by default)
// addressed to a real, currently-reachable HTTPS site. Two things ride inside
// that hello:
//
//   - a 16-byte authentication tag in the session_id field, derived from an
//     X25519 exchange between the client's ephemeral key and the relay's
//     long-term identity key — so only the intended relay can recognize it, and
//     no shared secret is distributed to clients;
//   - the client's own ephemeral X25519MLKEM768 key share, in the exact wire
//     format a real browser uses for that group.
//
// The relay peeks the first TLS record on every inbound connection:
//   - tag valid  -> a genuine Warren client. The relay answers with a
//     real-shaped TLS 1.3 ServerHello carrying the ML-KEM ciphertext, and both
//     sides derive the session key from ML-KEM + ephemeral X25519 + the
//     identity exchange (see handshake.go). Application data then flows in
//     records shaped like TLS application_data.
//   - tag invalid, absent, or replayed -> the connection is spliced
//     byte-for-byte to the real site the ClientHello's SNI names. A censor's
//     active probe (or any passive DPI classifier) sees a completely genuine
//     handshake with the real site's real certificate, because it *is* one.
//
// Known gap vs. full REALITY (xtls/xray-core's `reality` package): a genuine
// Warren session's second flight is shaped like TLS 1.3 but is not a real TLS
// handshake — there is no Certificate/Finished a probe holding a valid tag
// could verify, and Warren's own AEAD keys protect the session instead. Full
// REALITY keeps the borrowed site's real handshake all the way through. Closing
// that gap is tracked in docs/protocol/reality-transport.md; what this package
// does close is the static-PSK weakness (there is no longer a shared secret to
// leak) and the absence of post-quantum protection for recorded sessions.
package transport

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"time"

	utls "github.com/refraction-networking/utls"
)

// Config holds the parameters a camouflage client and relay need. A client
// needs ServerPublicKey; a relay needs ServerPrivateKey and FallbackAddr.
type Config struct {
	// ServerPublicKey is the relay's long-term X25519 public key (32 bytes),
	// distributed alongside its address in the bridge descriptor. Client side.
	ServerPublicKey []byte

	// ServerPrivateKey is the relay's long-term X25519 private key (32
	// bytes), generated by GenerateServerIdentity. Relay side; never leaves
	// the relay and never reaches a client.
	ServerPrivateKey []byte

	// FallbackSNI is the hostname the disguised ClientHello claims to be
	// visiting. The relay dials this host for real when a connection's tag
	// doesn't validate.
	FallbackSNI string

	// FallbackAddr is host:port for FallbackSNI (relay side only).
	FallbackAddr string

	// Fingerprint selects which browser ClientHello uTLS parrots. Zero value
	// means DefaultFingerprint.
	//
	// This is a perishable value, not a constant: browsers now offer a hybrid
	// post-quantum key share (X25519MLKEM768) by default, which makes a real
	// 2026 ClientHello both larger and structurally different from a 2023 one.
	// Parroting a profile that predates that shift is itself a distinguisher,
	// so the pinned profile has to keep moving. Per-region overrides matter too
	// — the right parrot is whatever the local population actually runs.
	Fingerprint utls.ClientHelloID
}

// DefaultFingerprint is the profile used when Config.Fingerprint is unset.
// HelloChrome_Auto tracks the newest Chrome profile uTLS ships, which is what
// keeps the hello's size and key_share groups inside the distribution of real
// browser traffic. TestDefaultFingerprintOffersHybridPQKeyShare guards the
// property that actually matters if this is ever pinned to a fixed version.
var DefaultFingerprint = utls.HelloChrome_Auto

// Dial opens a camouflaged connection to addr. On success the returned net.Conn
// transparently encrypts and decrypts application data under a session key both
// sides derived from the hybrid handshake; the caller does not need to know any
// of this happened.
func Dial(ctx context.Context, addr string, cfg Config) (net.Conn, error) {
	keys, err := newClientKeys(cfg.ServerPublicKey)
	if err != nil {
		return nil, err
	}

	d := net.Dialer{}
	raw, err := d.DialContext(ctx, "tcp", addr)
	if err != nil {
		return nil, fmt.Errorf("transport: dial %s: %w", addr, err)
	}

	if deadline, ok := ctx.Deadline(); ok {
		raw.SetDeadline(deadline)
	}

	fingerprint := cfg.Fingerprint
	if fingerprint.Client == "" {
		fingerprint = DefaultFingerprint
	}

	uconn := utls.UClient(raw, &utls.Config{ServerName: cfg.FallbackSNI}, fingerprint)
	if err := uconn.BuildHandshakeState(); err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: build client hello: %w", err)
	}

	hello := uconn.HandshakeState.Hello
	clientRandom := append([]byte(nil), hello.Random...)

	// Swap our own ephemeral keys into the hybrid key share. Same group, same
	// length, same structure as what uTLS generated, so the hello's shape is
	// untouched — only the bytes are ours, and only we hold the private halves.
	replaced := false
	for i := range hello.KeyShares {
		if hello.KeyShares[i].Group == utls.X25519MLKEM768 {
			hello.KeyShares[i].Data = keys.share
			replaced = true
			break
		}
	}
	if !replaced {
		raw.Close()
		return nil, fmt.Errorf("%w: fingerprint %v offers no hybrid group to hide the handshake in", ErrNoHybridShare, fingerprint)
	}

	sessionID := make([]byte, sessionIDLen)
	copy(sessionID, deriveTag(keys.authSS, clientRandom, keys.share))
	if _, err := io.ReadFull(randReader, sessionID[tagLen:]); err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: fill session id padding: %w", err)
	}
	hello.SessionId = sessionID

	// uTLS caches the originally-built wire bytes in hello.Raw and Marshal
	// returns that cache verbatim whenever it's non-nil — it does NOT
	// re-encode from the struct fields by default. Since we just mutated
	// SessionId and KeyShares, the cache is stale; clearing Raw forces Marshal
	// to actually re-serialize, picking up our patched fields while everything
	// else (extension order, cipher list, ALPN — the fingerprint proper) still
	// matches what uTLS built for the parroted browser profile.
	hello.Raw = nil
	rawHello, err := hello.Marshal()
	if err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: marshal client hello: %w", err)
	}

	record := make([]byte, 0, 5+len(rawHello))
	record = append(record, recordTypeHandshake, 0x03, 0x01) // legacy record version, as Chrome sends
	record = appendUint16(record, uint16(len(rawHello)))
	record = append(record, rawHello...)
	if _, err := raw.Write(record); err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: send client hello: %w", err)
	}

	br := bufio.NewReaderSize(raw, maxRecordLen+recordHeaderLen)
	serverHello, err := readRecord(br, recordTypeHandshake)
	if err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: read server hello: %w", err)
	}
	serverRandom, serverShare, err := parseServerHello(serverHello)
	if err != nil {
		raw.Close()
		return nil, err
	}

	// A real TLS 1.3 server in middlebox-compatibility mode follows its
	// ServerHello with a ChangeCipherSpec record, so ours does too — and the
	// client has to consume it before application data starts.
	if _, err := readRecord(br, recordTypeChangeCipherSpec); err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: read change_cipher_spec: %w", err)
	}

	mlkemSS, err := keys.mlkemDK.Decapsulate(serverShare[:mlkemCiphertextLen])
	if err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: decapsulate: %w", err)
	}
	serverECDHE, err := ecdhX25519PublicKey(serverShare[mlkemCiphertextLen:])
	if err != nil {
		raw.Close()
		return nil, err
	}
	ecdheSS, err := keys.ecdhe.ECDH(serverECDHE)
	if err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: ephemeral ecdh: %w", err)
	}

	sessionKey, err := deriveSessionKey(mlkemSS, ecdheSS, keys.authSS, clientRandom, serverRandom, keys.share, serverShare)
	if err != nil {
		raw.Close()
		return nil, err
	}

	// A real TLS 1.3 client in middlebox-compatibility mode (which is what
	// sending a non-empty session_id signals) answers the ServerHello with a
	// ChangeCipherSpec record before its encrypted flight. Ours does the same,
	// so the record sequence on the wire keeps matching a genuine session.
	if _, err := raw.Write(changeCipherSpecRecord()); err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: send change_cipher_spec: %w", err)
	}

	// Clear the handshake deadline: the caller's context bounded the
	// handshake, not the lifetime of the tunnel.
	raw.SetDeadline(time.Time{})

	conn, err := newAEADConn(&bufferedConn{Conn: raw, r: br}, sessionKey, true /* isClient */)
	if err != nil {
		raw.Close()
		return nil, err
	}
	return conn, nil
}

// Handler processes an authenticated Warren connection. Implementations own
// the lifetime of conn and must close it when done.
type Handler func(conn net.Conn)

// Serve accepts connections on ln, validating each one's embedded tag. Valid
// connections are handed to handle over an AEAD-framed net.Conn; invalid,
// absent, or replayed tags cause the raw bytes to be spliced to
// cfg.FallbackAddr so the connection completes as a genuine visit to the real
// site.
func Serve(ctx context.Context, ln net.Listener, cfg Config, handle Handler) error {
	replays := newReplayCache()
	for {
		raw, err := ln.Accept()
		if err != nil {
			if ctx.Err() != nil {
				return nil
			}
			return err
		}
		go serveConn(ctx, raw, cfg, replays, handle)
	}
}

// sniffTimeout bounds how long we'll wait for a complete ClientHello before
// giving up. Without this, a connection that sends a plausible record header
// claiming a large record but never sends the rest would block its serveConn
// goroutine forever (a cheap Slowloris-style resource exhaustion — one
// dangling TCP connection per idle goroutine).
//
// It has to accommodate a legitimate hybrid ClientHello, which is ~1.5 KB and
// therefore arrives across several TCP segments rather than in one.
const sniffTimeout = 5 * time.Second

func serveConn(ctx context.Context, raw net.Conn, cfg Config, replays *replayCache, handle Handler) {
	br := bufio.NewReaderSize(raw, maxRecordLen+recordHeaderLen)

	raw.SetReadDeadline(time.Now().Add(sniffTimeout))

	// Any failure below — malformed record, short read, tag mismatch, replay —
	// is treated identically: fall through to the fallback splice. Closing the
	// connection instead on a parse failure would itself be a distinguishing
	// signal (a real HTTPS server doesn't instantly RST on odd input), so we
	// deliberately don't special-case parse errors from tag mismatches.
	hello, recordLen, err := peekClientHello(br)
	if err == nil {
		serverHello, sessionKey, acceptErr := serverAccept(
			cfg.ServerPrivateKey, hello.Random, hello.SessionId, hello.share)

		if acceptErr == nil && replays.admit(hello.Random) {
			raw.SetReadDeadline(time.Now().Add(sniffTimeout))
			err := completeHandshake(raw, br, recordLen, serverHello)
			raw.SetReadDeadline(time.Time{})
			if err != nil {
				raw.Close()
				return
			}
			conn, err := newAEADConn(&bufferedConn{Conn: raw, r: br}, sessionKey, false /* isClient */)
			if err != nil {
				raw.Close()
				return
			}
			handle(conn)
			return
		}
	}

	raw.SetReadDeadline(time.Time{})

	// Not a Warren client (or a censor's probe) — splice to the real site
	// so whatever they see is indistinguishable from a normal visit.
	spliceToFallback(ctx, raw, br, cfg.FallbackAddr)
}

// completeHandshake consumes the client's ClientHello record, sends the
// ServerHello and a ChangeCipherSpec, and consumes the client's own
// ChangeCipherSpec, leaving the stream positioned at the first application
// data record.
func completeHandshake(raw net.Conn, br *bufio.Reader, helloRecordLen int, serverHello []byte) error {
	// Consume the *entire* ClientHello record, not just the prefix we peeked:
	// extensions and key shares still follow it on the wire and would
	// otherwise be misread as the first application data record.
	if _, err := br.Discard(helloRecordLen); err != nil {
		return err
	}
	if _, err := raw.Write(serverHello); err != nil {
		return err
	}
	if _, err := raw.Write(changeCipherSpecRecord()); err != nil {
		return err
	}
	if _, err := readRecord(br, recordTypeChangeCipherSpec); err != nil {
		return err
	}
	return nil
}

// parsedClientHello is the parsed hello plus the hybrid key share we need.
type parsedClientHello struct {
	*utls.PubClientHelloMsg
	share []byte
}

// peekClientHello reads a complete TLS record containing a ClientHello from r
// without consuming it, and parses it. Peeking the whole record (rather than
// reading a fixed-offset prefix) is what makes a segmented arrival a non-issue:
// bufio blocks until the record is complete or the sniff deadline fires, and on
// the fallback path every original byte is still in the buffer to be spliced.
func peekClientHello(r *bufio.Reader) (*parsedClientHello, int, error) {
	head, err := r.Peek(recordHeaderLen + 1)
	if err != nil {
		return nil, 0, ErrShortRead
	}
	if head[0] != recordTypeHandshake || head[5] != 0x01 /* client_hello */ {
		return nil, 0, ErrNotClientHello
	}
	bodyLen := int(head[3])<<8 | int(head[4])
	if bodyLen < 4 || bodyLen > maxRecordLen {
		return nil, 0, ErrNotClientHello
	}
	recordLen := recordHeaderLen + bodyLen

	record, err := r.Peek(recordLen)
	if err != nil {
		return nil, 0, ErrShortRead
	}

	msg := utls.UnmarshalClientHello(record[recordHeaderLen:])
	if msg == nil || len(msg.Random) != 32 || len(msg.SessionId) != sessionIDLen {
		return nil, 0, ErrNotClientHello
	}
	share, err := hybridShare(msg.KeyShares)
	if err != nil {
		return nil, 0, err
	}
	return &parsedClientHello{PubClientHelloMsg: msg, share: share}, recordLen, nil
}

func spliceToFallback(ctx context.Context, raw net.Conn, br *bufio.Reader, fallbackAddr string) {
	defer raw.Close()
	d := net.Dialer{Timeout: 5 * time.Second}
	upstream, err := d.DialContext(ctx, "tcp", fallbackAddr)
	if err != nil {
		return
	}
	defer upstream.Close()

	done := make(chan struct{}, 2)
	go func() { io.Copy(upstream, br); done <- struct{}{} }()
	go func() { io.Copy(raw, upstream); done <- struct{}{} }()
	<-done
}

// bufferedConn lets us keep using a bufio.Reader (which may already hold
// buffered bytes past the handshake) as a net.Conn for the AEAD layer.
type bufferedConn struct {
	net.Conn
	r *bufio.Reader
}

func (b *bufferedConn) Read(p []byte) (int, error) { return b.r.Read(p) }

var errUnexpectedRecordType = errors.New("transport: unexpected TLS record type")
