// Package transport implements Warren's L1 protocol camouflage layer.
//
// A Warren client's first packet is a syntactically valid TLS 1.3 ClientHello
// (built with uTLS so it carries a current browser's fingerprint, including the
// hybrid post-quantum key share mainstream browsers now offer by default)
// addressed to a real, currently-reachable HTTPS site. Two things ride inside
// that hello:
//
//   - a 16-byte authentication tag in the session_id field, derived from an
//     X25519 exchange between the client's ephemeral key and the relay's
//     long-term identity key — so only the intended relay can recognize it, and
//     no shared secret is distributed to clients;
//   - the client's own ephemeral X25519MLKEM768 key share, in the exact wire
//     format a real browser uses for that group.
//
// The relay peeks the first TLS record on every inbound connection:
//   - tag valid  -> a genuine Warren client. The relay answers with a
//     real-shaped TLS 1.3 ServerHello carrying the ML-KEM ciphertext, and both
//     sides derive the session key from ML-KEM + ephemeral X25519 + the
//     identity exchange (see handshake.go). Application data then flows in
//     records shaped like TLS application_data.
//   - tag invalid, absent, or replayed -> the connection is spliced
//     byte-for-byte to the real site the ClientHello's SNI names. A censor's
//     active probe (or any passive DPI classifier) sees a completely genuine
//     handshake with the real site's real certificate, because it *is* one.
//
// Known gap vs. full REALITY (xtls/xray-core's `reality` package): a genuine
// Warren session's second flight is shaped like TLS 1.3 but is not a real TLS
// handshake — there is no Certificate/Finished a probe holding a valid tag
// could verify, and Warren's own AEAD keys protect the session instead. Full
// REALITY keeps the borrowed site's real handshake all the way through. Closing
// that gap is tracked in docs/protocol/reality-transport.md; what this package
// does close is the static-PSK weakness (there is no longer a shared secret to
// leak) and the absence of post-quantum protection for recorded sessions.
package transport

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"sync/atomic"
	"time"

	utls "github.com/refraction-networking/utls"
)

// Config holds the parameters a camouflage client and relay need. A client
// needs ServerPublicKey; a relay needs ServerPrivateKey and FallbackAddr.
type Config struct {
	// ServerPublicKey is the relay's long-term X25519 public key (32 bytes),
	// distributed alongside its address in the bridge descriptor. Client side.
	ServerPublicKey []byte

	// ServerPrivateKey is the relay's long-term X25519 private key (32
	// bytes), generated by GenerateServerIdentity. Relay side; never leaves
	// the relay and never reaches a client.
	ServerPrivateKey []byte

	// FallbackSNI is the hostname the disguised ClientHello claims to be
	// visiting. The relay dials this host for real when a connection's tag
	// doesn't validate.
	FallbackSNI string

	// FallbackAddr is host:port for FallbackSNI (relay side only).
	FallbackAddr string

	// Flight is the borrowed site's measured record shape, from ProfileSite.
	// Relay side, and required: without it the relay would answer its
	// ServerHello with silence where a real server sends a kilobytes-long
	// encrypted certificate flight, which is separable on record sizes alone.
	// Serve refuses to start rather than serve a shape that advertises itself.
	Flight *FlightProfile

	// FlightFunc, when set, supersedes Flight and is consulted per connection.
	// A relay re-measures its borrowed site periodically (certificates rotate,
	// TLS stacks get reconfigured), and AtomicFlight.Load is the intended value
	// here. If it ever returns something unusable, the relay splices that
	// connection to the real site instead of serving a shape it cannot trust.
	FlightFunc func() *FlightProfile

	// Fingerprint selects which browser ClientHello uTLS parrots. Zero value
	// means DefaultFingerprint.
	//
	// This is a perishable value, not a constant: browsers now offer a hybrid
	// post-quantum key share (X25519MLKEM768) by default, which makes a real
	// 2026 ClientHello both larger and structurally different from a 2023 one.
	// Parroting a profile that predates that shift is itself a distinguisher,
	// so the pinned profile has to keep moving. Per-region overrides matter too
	// — the right parrot is whatever the local population actually runs.
	Fingerprint utls.ClientHelloID
}

// flight returns the profile this relay should imitate right now.
func (c Config) flight() *FlightProfile {
	if c.FlightFunc != nil {
		return c.FlightFunc()
	}
	return c.Flight
}

// DefaultFingerprint is the profile used when Config.Fingerprint is unset.
// HelloChrome_Auto tracks the newest Chrome profile uTLS ships, which is what
// keeps the hello's size and key_share groups inside the distribution of real
// browser traffic. TestDefaultFingerprintOffersHybridPQKeyShare guards the
// property that actually matters if this is ever pinned to a fixed version.
var DefaultFingerprint = utls.HelloChrome_Auto

// Dial opens a camouflaged connection to addr. On success the returned net.Conn
// transparently encrypts and decrypts application data under a session key both
// sides derived from the hybrid handshake; the caller does not need to know any
// of this happened.
func Dial(ctx context.Context, addr string, cfg Config) (net.Conn, error) {
	keys, err := newClientKeys(cfg.ServerPublicKey)
	if err != nil {
		return nil, err
	}

	d := net.Dialer{}
	raw, err := d.DialContext(ctx, "tcp", addr)
	if err != nil {
		return nil, fmt.Errorf("transport: dial %s: %w", addr, err)
	}

	if deadline, ok := ctx.Deadline(); ok {
		raw.SetDeadline(deadline)
	}

	fingerprint := cfg.Fingerprint
	if fingerprint.Client == "" {
		fingerprint = DefaultFingerprint
	}

	uconn := utls.UClient(raw, &utls.Config{ServerName: cfg.FallbackSNI}, fingerprint)
	if err := uconn.BuildHandshakeState(); err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: build client hello: %w", err)
	}

	hello := uconn.HandshakeState.Hello
	clientRandom := append([]byte(nil), hello.Random...)

	// Swap our own ephemeral keys into the hybrid key share. Same group, same
	// length, same structure as what uTLS generated, so the hello's shape is
	// untouched — only the bytes are ours, and only we hold the private halves.
	//
	// The bytes that actually go on the wire come from the *extension* objects
	// in uconn.Extensions, not from the PubClientHelloMsg fields, so the key
	// share has to be patched there. Both are updated: the extension is what
	// gets marshaled, and hello.KeyShares is what uTLS reads if it ever takes
	// the ECH path.
	replaced := false
	for _, ext := range uconn.Extensions {
		ks, ok := ext.(*utls.KeyShareExtension)
		if !ok {
			continue
		}
		for i := range ks.KeyShares {
			if ks.KeyShares[i].Group == utls.X25519MLKEM768 {
				ks.KeyShares[i].Data = keys.share
				replaced = true
			}
		}
	}
	for i := range hello.KeyShares {
		if hello.KeyShares[i].Group == utls.X25519MLKEM768 {
			hello.KeyShares[i].Data = keys.share
		}
	}
	if !replaced {
		raw.Close()
		return nil, fmt.Errorf("%w: fingerprint %v offers no hybrid group to hide the handshake in", ErrNoHybridShare, fingerprint)
	}

	sessionID := make([]byte, sessionIDLen)
	copy(sessionID, deriveTag(keys.authSS, clientRandom, keys.share, tagWindowIndex(time.Now())))
	if _, err := io.ReadFull(randReader, sessionID[tagLen:]); err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: fill session id padding: %w", err)
	}
	hello.SessionId = sessionID

	// Marshal through uTLS rather than through PubClientHelloMsg.Marshal().
	// The struct-field marshaler only emits the extensions it knows about and
	// drops everything that lives solely in uconn.Extensions — for a current
	// Chrome profile that includes the GREASE ECH block, which is a couple of
	// hundred bytes. Using it produced a hello ~250 bytes shorter than the
	// profile it claimed to be, a distinguisher on the very first packet. The
	// probe harness (internal/network/probe) is what caught it, which is the
	// argument for having the harness at all.
	if err := uconn.MarshalClientHello(); err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: marshal client hello: %w", err)
	}
	rawHello := hello.Raw

	record := make([]byte, 0, 5+len(rawHello))
	record = append(record, recordTypeHandshake, 0x03, 0x01) // legacy record version, as Chrome sends
	record = appendUint16(record, uint16(len(rawHello)))
	record = append(record, rawHello...)
	if _, err := raw.Write(record); err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: send client hello: %w", err)
	}

	br := bufio.NewReaderSize(raw, maxRecordLen+recordHeaderLen)
	serverHello, err := readRecord(br, recordTypeHandshake)
	if err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: read server hello: %w", err)
	}
	serverRandom, serverShare, err := parseServerHello(serverHello)
	if err != nil {
		raw.Close()
		return nil, err
	}

	// A real TLS 1.3 server in middlebox-compatibility mode follows its
	// ServerHello with a ChangeCipherSpec record, so ours does too — and the
	// client has to consume it before application data starts.
	if _, err := readRecord(br, recordTypeChangeCipherSpec); err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: read change_cipher_spec: %w", err)
	}

	mlkemSS, err := keys.mlkemDK.Decapsulate(serverShare[:mlkemCiphertextLen])
	if err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: decapsulate: %w", err)
	}
	serverECDHE, err := ecdhX25519PublicKey(serverShare[mlkemCiphertextLen:])
	if err != nil {
		raw.Close()
		return nil, err
	}
	ecdheSS, err := keys.ecdhe.ECDH(serverECDHE)
	if err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: ephemeral ecdh: %w", err)
	}

	sessionKey, err := deriveSessionKey(mlkemSS, ecdheSS, keys.authSS, clientRandom, serverRandom, keys.share, serverShare)
	if err != nil {
		raw.Close()
		return nil, err
	}

	conn, err := newAEADConn(&bufferedConn{Conn: raw, r: br}, sessionKey, true /* isClient */)
	if err != nil {
		raw.Close()
		return nil, err
	}

	// The relay now sends what a real server would: an encrypted flight the size
	// of the borrowed site's certificate flight, with Warren's key confirmation
	// inside the largest record. Reading it to completion before answering is
	// what keeps the record order matching a real session — a real client's
	// ChangeCipherSpec and Finished come after the server's flight, not before.
	serverMAC := confirmation(sessionKey, serverConfirmLabel, clientRandom, keys.share, serverRandom, serverShare)
	confirm, err := conn.readServerFlight(serverMAC)
	if err != nil {
		raw.Close()
		// This is where being spliced surfaces, and it surfaces as garbage: a
		// relay that did not recognise the tag hands the connection to the site
		// it borrows, so everything after the ServerHello is that site's real
		// TLS session and none of it opens under our key. The raw error is an
		// AEAD failure, which says nothing useful to whoever is trying to
		// connect, so the likely causes get named here instead.
		return nil, fmt.Errorf("%w: %v", ErrRelayRejected, err)
	}

	// A real TLS 1.3 client in middlebox-compatibility mode (which is what
	// sending a non-empty session_id signals) sends a ChangeCipherSpec followed
	// by its Finished. Ours sends the same two records, the second sized to what
	// the relay measured a real client's Finished to be against that site.
	if _, err := raw.Write(changeCipherSpecRecord()); err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: send change_cipher_spec: %w", err)
	}

	finishedLen := confirm.ClientFinishedLen
	if finishedLen < aeadRecordOverhead+flightHeaderLen+1+minConfirmationBytes {
		finishedLen = defaultFinishedRecordLen
	}
	clientMAC := confirmation(sessionKey, clientConfirmLabel, clientRandom, keys.share, serverRandom, serverShare)
	if err := conn.writeFrame(kindConfirm, clientConfirmPayload(clientMAC, finishedLen), finishedLen); err != nil {
		raw.Close()
		return nil, fmt.Errorf("transport: send client confirmation: %w", err)
	}

	// Clear the handshake deadline: the caller's context bounded the handshake,
	// not the lifetime of the tunnel.
	raw.SetDeadline(time.Time{})
	return conn, nil
}

// defaultFinishedRecordLen is what a real TLS 1.3 client's Finished record
// measures for a SHA-256 cipher suite, which is what Warren's ServerHello
// selects: 4 bytes of handshake header, a 32-byte verify_data, one byte of inner
// content type, and a 16-byte tag. Used only if a profile somehow carries an
// implausible measurement.
const defaultFinishedRecordLen = 4 + 32 + 1 + 16

// Handler processes an authenticated Warren connection. Implementations own
// the lifetime of conn and must close it when done.
type Handler func(conn net.Conn)

// Serve accepts connections on ln, validating each one's embedded tag. Valid
// connections are handed to handle over an AEAD-framed net.Conn; invalid,
// absent, or replayed tags cause the raw bytes to be spliced to
// cfg.FallbackAddr so the connection completes as a genuine visit to the real
// site.
func Serve(ctx context.Context, ln net.Listener, cfg Config, handle Handler) error {
	// Fail closed on a missing or implausible flight profile. A relay that
	// cannot imitate its borrowed site's handshake is a relay that announces
	// itself to anyone measuring record sizes, and quietly serving clients
	// anyway would put them at more risk than not running at all.
	if err := cfg.flight().Validate(); err != nil {
		return err
	}

	replays := newReplayCache()
	for {
		raw, err := ln.Accept()
		if err != nil {
			if ctx.Err() != nil {
				return nil
			}
			return err
		}
		go serveConn(ctx, raw, cfg, replays, handle)
	}
}

// sniffTimeout bounds how long we'll wait for a complete ClientHello before
// giving up. Without this, a connection that sends a plausible record header
// claiming a large record but never sends the rest would block its serveConn
// goroutine forever (a cheap Slowloris-style resource exhaustion — one
// dangling TCP connection per idle goroutine).
//
// It has to accommodate a legitimate hybrid ClientHello, which is ~1.5 KB and
// therefore arrives across several TCP segments rather than in one.
const sniffTimeout = 5 * time.Second

// spliceDrainGrace is how long the relay keeps relaying the borrowed site's
// answer after the client has stopped sending. It exists so a response is never
// cut short — a truncated answer is a difference from the site, and the site
// does not truncate — and it is bounded so a site that goes quiet cannot hold
// the connection, and the goroutine behind it, indefinitely.
const spliceDrainGrace = 5 * time.Second

func serveConn(ctx context.Context, raw net.Conn, cfg Config, replays *replayCache, handle Handler) {
	br := bufio.NewReaderSize(raw, maxRecordLen+recordHeaderLen)

	raw.SetReadDeadline(time.Now().Add(sniffTimeout))

	// Any failure below — malformed record, short read, tag mismatch, replay —
	// is treated identically: fall through to the fallback splice. Closing the
	// connection instead on a parse failure would itself be a distinguishing
	// signal (a real HTTPS server doesn't instantly RST on odd input), so we
	// deliberately don't special-case parse errors from tag mismatches.
	hello, recordLen, err := peekClientHello(br)
	// Timestamped here rather than inside completeHandshake: the answer latency
	// the relay has to reproduce is measured from the arrival of the hello, so
	// the key exchange below has to fall inside that budget rather than extend it.
	helloAt := time.Now()
	if err == nil {
		accepted, acceptErr := serverAccept(
			cfg.ServerPrivateKey, hello.random, hello.sessionID, hello.share, helloAt)

		flight := cfg.flight()
		if acceptErr == nil && flight.Validate() == nil && replays.admit(hello.random, helloAt) {
			raw.SetReadDeadline(time.Now().Add(sniffTimeout + maxServerHelloDelay))
			conn, err := completeHandshake(raw, br, recordLen, helloAt, accepted, flight, hello.random, hello.share)
			raw.SetReadDeadline(time.Time{})
			if err != nil {
				raw.Close()
				return
			}
			handle(conn)
			return
		}
	}

	raw.SetReadDeadline(time.Time{})

	// Not a Warren client (or a censor's probe) — splice to the real site
	// so whatever they see is indistinguishable from a normal visit.
	spliceToFallback(ctx, raw, br, cfg.FallbackAddr)
}

// completeHandshake plays the relay's half of a session that has to look like a
// real TLS 1.3 handshake: ServerHello, ChangeCipherSpec, the shaped flight
// standing in for the certificate messages, then the client's ChangeCipherSpec
// and Finished, then whatever the borrowed site sends afterwards (tickets).
func completeHandshake(
	raw net.Conn,
	br *bufio.Reader,
	helloRecordLen int,
	helloAt time.Time,
	accepted *acceptResult,
	flight *FlightProfile,
	clientRandom, clientShare []byte,
) (net.Conn, error) {
	// Consume the *entire* ClientHello record, not just the prefix we peeked:
	// extensions and key shares still follow it on the wire and would otherwise
	// be misread as the first application data record.
	if _, err := br.Discard(helloRecordLen); err != nil {
		return nil, err
	}

	// Answer no faster than the borrowed site does. The relay's other path —
	// splicing an unauthenticated connection — pays a TCP dial to that site plus
	// the site's own answer time, so without this wait one relay IP answers some
	// connections in microseconds and the rest tens of milliseconds later. That
	// split is visible to a passive observer with a clock and nothing else.
	//
	// The wait is measured from when the ClientHello landed, not from here, so
	// the key exchange we just did comes out of the same budget rather than
	// being added to it.
	waitUntilAnswerTime(helloAt, flight.ServerHelloDelay)

	if _, err := raw.Write(accepted.serverHello); err != nil {
		return nil, err
	}
	if _, err := raw.Write(changeCipherSpecRecord()); err != nil {
		return nil, err
	}

	conn, err := newAEADConn(&bufferedConn{Conn: raw, r: br}, accepted.sessionKey, false /* isClient */)
	if err != nil {
		return nil, err
	}

	serverMAC := confirmation(accepted.sessionKey, serverConfirmLabel,
		clientRandom, clientShare, accepted.serverRandom, accepted.serverShare)
	if err := conn.sendShapedFlight(flight, serverMAC); err != nil {
		return nil, err
	}

	if _, err := readRecord(br, recordTypeChangeCipherSpec); err != nil {
		return nil, err
	}

	expected := confirmation(accepted.sessionKey, clientConfirmLabel,
		clientRandom, clientShare, accepted.serverRandom, accepted.serverShare)
	if err := conn.readClientConfirmation(expected); err != nil {
		return nil, err
	}

	if err := conn.sendPostClientFlight(flight); err != nil {
		return nil, err
	}
	return conn, nil
}

// waitUntilAnswerTime sleeps so that `delay` has elapsed since `since`,
// accounting for work already done. It is capped rather than trusted: a profile
// carrying an implausible delay would otherwise let a slow or hostile borrowed
// site hold every Warren handshake open for as long as it likes.
func waitUntilAnswerTime(since time.Time, delay time.Duration) {
	if delay <= 0 {
		return
	}
	if delay > maxServerHelloDelay {
		delay = maxServerHelloDelay
	}
	if remaining := delay - time.Since(since); remaining > 0 {
		time.Sleep(remaining)
	}
}

// parsedClientHello is the handful of ClientHello fields the relay needs, held
// in slices it owns.
//
// Owning them matters: uTLS parses zero-copy, so a parsed hello points into the
// bufio buffer the record was peeked from, and every subsequent read on that
// reader overwrites those bytes. The tag check happens before any further read,
// but the key confirmation in the shaped flight is computed after the client's
// own records have come in — at which point an aliased slice holds whatever
// arrived last. That bug is invisible in a single-round-trip test and shows up
// as an intermittent confirmation failure under load.
type parsedClientHello struct {
	random    []byte
	sessionID []byte
	share     []byte
}

// peekClientHello reads a complete TLS record containing a ClientHello from r
// without consuming it, and parses it. Peeking the whole record (rather than
// reading a fixed-offset prefix) is what makes a segmented arrival a non-issue:
// bufio blocks until the record is complete or the sniff deadline fires, and on
// the fallback path every original byte is still in the buffer to be spliced.
func peekClientHello(r *bufio.Reader) (*parsedClientHello, int, error) {
	head, err := r.Peek(recordHeaderLen + 1)
	if err != nil {
		return nil, 0, ErrShortRead
	}
	if head[0] != recordTypeHandshake || head[5] != 0x01 /* client_hello */ {
		return nil, 0, ErrNotClientHello
	}
	bodyLen := int(head[3])<<8 | int(head[4])
	if bodyLen < 4 || bodyLen > maxRecordLen {
		return nil, 0, ErrNotClientHello
	}
	recordLen := recordHeaderLen + bodyLen

	record, err := r.Peek(recordLen)
	if err != nil {
		return nil, 0, ErrShortRead
	}

	msg := utls.UnmarshalClientHello(record[recordHeaderLen:])
	if msg == nil || len(msg.Random) != 32 || len(msg.SessionId) != sessionIDLen {
		return nil, 0, ErrNotClientHello
	}
	share, err := hybridShare(msg.KeyShares)
	if err != nil {
		return nil, 0, err
	}
	return &parsedClientHello{
		random:    append([]byte(nil), msg.Random...),
		sessionID: append([]byte(nil), msg.SessionId...),
		share:     append([]byte(nil), share...),
	}, recordLen, nil
}

func spliceToFallback(ctx context.Context, raw net.Conn, br *bufio.Reader, fallbackAddr string) {
	// How the connection *ends* is observable too. A real HTTPS server given
	// plaintext HTTP typically aborts with an RST; if the relay answers the same
	// request by relaying the site's bytes and then closing cleanly with a FIN,
	// the pair is separable on TCP teardown alone — no TLS analysis needed. So
	// the teardown is mirrored: if the upstream reset, so do we.
	//
	// The probe harness (internal/network/probe) found this by comparing a relay
	// against an OpenSSL-backed site; a Go-backed site closes cleanly and hid it.
	//
	// Whether a given error *is* a reset is platform-specific (see isConnReset):
	// on Windows the portable-looking syscall.ECONNRESET never matches a real
	// one, which left this mirroring dead on that platform for as long as CI
	// only ran Linux.
	var upstreamReset atomic.Bool
	defer func() {
		if upstreamReset.Load() {
			if tcp, ok := raw.(*net.TCPConn); ok {
				tcp.SetLinger(0) // makes the following Close send an RST
			}
		}
		raw.Close()
	}()

	d := net.Dialer{Timeout: 5 * time.Second}
	upstream, err := d.DialContext(ctx, "tcp", fallbackAddr)
	if err != nil {
		return
	}
	defer upstream.Close()

	// Client -> site. A reset here shows up as a *write* failure, so the writer
	// is wrapped rather than the error being inspected afterwards: io.Copy
	// returns one error and does not say which side produced it, and a reset
	// from the client is not something to mirror back to that same client.
	// Nothing is lost by wrapping — br is a bufio.Reader, so this direction has
	// no kernel fast path to give up.
	toSite := make(chan struct{})
	go func() {
		defer close(toSite)
		io.Copy(&resetWatchingWriter{w: upstream, hit: &upstreamReset}, br)
	}()

	// Site -> client. Left unwrapped so io.Copy keeps its TCPConn-to-TCPConn
	// fast path (splice(2) on Linux), which this direction carries the bulk of.
	// The error is therefore ambiguous between a read failure from the site and
	// a write failure to the client, and that is acceptable: if the client is
	// the one that reset, the connection is already gone and marking it for a
	// reset teardown changes nothing observable.
	fromSite := make(chan struct{})
	go func() {
		defer close(fromSite)
		_, err := io.Copy(raw, upstream)
		if isConnReset(err) {
			upstreamReset.Store(true)
		}
	}()

	// The two directions are not interchangeable, which is why this waits on
	// one of them by name rather than on whichever finishes first.
	//
	// The site's answer is the whole point of the splice: a probe judges the
	// relay on what comes back, so relaying part of a response and then closing
	// is itself a difference from the site, which always finishes what it
	// started. Waiting on "either direction, then a fixed 200 ms" truncated
	// exactly that — when the site closed its end straight after answering, the
	// client-to-site copy could return first and start a grace period the
	// response then had to beat. It usually did, and under load it sometimes
	// did not, which showed up as the relay answering a probe with nothing
	// where the site answered with an alert.
	select {
	case <-fromSite:
		// The site has finished; anything still travelling the other way has
		// nowhere to go.
	case <-toSite:
		// The client stopped sending, which says nothing about whether the
		// site has finished replying. Give it room to, bounded so a site that
		// simply never answers cannot pin this connection open.
		select {
		case <-fromSite:
		case <-time.After(spliceDrainGrace):
		}
	}
}

// resetWatchingWriter records whether writes to this particular side failed
// with a peer reset, so the two halves of a splice can be told apart.
type resetWatchingWriter struct {
	w   io.Writer
	hit *atomic.Bool
}

func (w *resetWatchingWriter) Write(p []byte) (int, error) {
	n, err := w.w.Write(p)
	if err != nil && isConnReset(err) {
		w.hit.Store(true)
	}
	return n, err
}

// bufferedConn lets us keep using a bufio.Reader (which may already hold
// buffered bytes past the handshake) as a net.Conn for the AEAD layer.
type bufferedConn struct {
	net.Conn
	r *bufio.Reader
}

func (b *bufferedConn) Read(p []byte) (int, error) { return b.r.Read(p) }

var errUnexpectedRecordType = errors.New("transport: unexpected TLS record type")
